// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRPSbBR9v9fWcPRXRmHibm_Qa796nuRAI',
    appId: '1:142725166511:android:d5dcfe9ef9bb91c6c92b5a',
    messagingSenderId: '142725166511',
    projectId: 'chatting-app-759a0',
    storageBucket: 'chatting-app-759a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA63Bjybn1fB4V14FAmkTp4l8Qy6YTSwV0',
    appId: '1:142725166511:ios:3976a1fd6d3697f6c92b5a',
    messagingSenderId: '142725166511',
    projectId: 'chatting-app-759a0',
    storageBucket: 'chatting-app-759a0.appspot.com',
    androidClientId: '142725166511-ikq6ctob20uu20dt1hrognj4kougffvp.apps.googleusercontent.com',
    iosClientId: '142725166511-qttm3ddm0mp84a9l8g26fii2j8sg5qj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );
}
